robot:
  type: so101_follower
  port: /dev/ttyACM0
  id: my_awesome_follower_arm
  cameras:
    top:
      type: opencv
      index_or_path: 10
      width: 640
      height: 480
      fps: 30
      fourcc: MJPG
    front:
      type: opencv
      index_or_path: 8
      width: 640
      height: 480
      fps: 30
      fourcc: MJPG
    wrist:
      type: opencv
      index_or_path: 6
      width: 640
      height: 480
      fps: 30
      fourcc: MJPG

dataset:
  repo_id: qwzy123/eval_cup_stacking
  single_task: "Stack the red cup on another cup"
  num_episodes: 10
  episode_time_s: 60
  push_to_hub: false
